/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WifiRouteImport } from './routes/wifi'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as QrRouteImport } from './routes/qr'
import { Route as InfoRouteImport } from './routes/info'
import { Route as ExcursionsRouteImport } from './routes/excursions'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BeachesRouteImport } from './routes/beaches'
import { Route as IndexRouteImport } from './routes/index'

const WifiRoute = WifiRouteImport.update({
  id: '/wifi',
  path: '/wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionsRoute = ExcursionsRouteImport.update({
  id: '/excursions',
  path: '/excursions',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BeachesRoute = BeachesRouteImport.update({
  id: '/beaches',
  path: '/beaches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beaches': typeof BeachesRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/excursions': typeof ExcursionsRoute
  '/info': typeof InfoRoute
  '/qr': typeof QrRoute
  '/restaurants': typeof RestaurantsRoute
  '/shopping': typeof ShoppingRoute
  '/wifi': typeof WifiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beaches': typeof BeachesRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/excursions': typeof ExcursionsRoute
  '/info': typeof InfoRoute
  '/qr': typeof QrRoute
  '/restaurants': typeof RestaurantsRoute
  '/shopping': typeof ShoppingRoute
  '/wifi': typeof WifiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beaches': typeof BeachesRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/excursions': typeof ExcursionsRoute
  '/info': typeof InfoRoute
  '/qr': typeof QrRoute
  '/restaurants': typeof RestaurantsRoute
  '/shopping': typeof ShoppingRoute
  '/wifi': typeof WifiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beaches'
    | '/contact'
    | '/emergency'
    | '/excursions'
    | '/info'
    | '/qr'
    | '/restaurants'
    | '/shopping'
    | '/wifi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beaches'
    | '/contact'
    | '/emergency'
    | '/excursions'
    | '/info'
    | '/qr'
    | '/restaurants'
    | '/shopping'
    | '/wifi'
  id:
    | '__root__'
    | '/'
    | '/beaches'
    | '/contact'
    | '/emergency'
    | '/excursions'
    | '/info'
    | '/qr'
    | '/restaurants'
    | '/shopping'
    | '/wifi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeachesRoute: typeof BeachesRoute
  ContactRoute: typeof ContactRoute
  EmergencyRoute: typeof EmergencyRoute
  ExcursionsRoute: typeof ExcursionsRoute
  InfoRoute: typeof InfoRoute
  QrRoute: typeof QrRoute
  RestaurantsRoute: typeof RestaurantsRoute
  ShoppingRoute: typeof ShoppingRoute
  WifiRoute: typeof WifiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wifi': {
      id: '/wifi'
      path: '/wifi'
      fullPath: '/wifi'
      preLoaderRoute: typeof WifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excursions': {
      id: '/excursions'
      path: '/excursions'
      fullPath: '/excursions'
      preLoaderRoute: typeof ExcursionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaches': {
      id: '/beaches'
      path: '/beaches'
      fullPath: '/beaches'
      preLoaderRoute: typeof BeachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeachesRoute: BeachesRoute,
  ContactRoute: ContactRoute,
  EmergencyRoute: EmergencyRoute,
  ExcursionsRoute: ExcursionsRoute,
  InfoRoute: InfoRoute,
  QrRoute: QrRoute,
  RestaurantsRoute: RestaurantsRoute,
  ShoppingRoute: ShoppingRoute,
  WifiRoute: WifiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
